[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-is-permission-granted",
    "allow-request-permission",
    "allow-notify",
    "allow-register-action-types",
    "allow-register-listener",
    "allow-cancel",
    "allow-get-pending",
    "allow-remove-active",
    "allow-get-active",
    "allow-check-permissions",
    "allow-show",
    "allow-batch",
    "allow-list-channels",
    "allow-delete-channel",
    "allow-create-channel",
    "allow-permission-state"
]
